default: &shared
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: "flash-example"

development:
  <<: *shared

test:
  <<: *shared
  database: flash-example-test

production:
  <<: *shared
