# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3f46b387ea6c9ccbd0d2f472ccf6ec58148ae920072b02ce08872a6616532fa73628097506ec1996e89b66725fbbd561d71c5df376d248352bd9f666a91314a

test:
  secret_key_base: df21464a8db4531293695fd4b425b00d43dd06c376a18032f450487b02daa6604703e5a9eebac9bf2261d87c6835875c370c424953dad4ac6bdfae38bc011679

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
